version: 2
jobs:
  test:
    docker:
      - image: cimg/go:1.21.1
    working_directory: /go/src/github.com/unchain1ed/webapp/server-app
    
    steps:
      - checkout  # デフォルトでリポジトリをクローンするステップ

      # 新しいリポジトリのURLで git clone を実行するステップを追加
      - run:
          name: Clone webapp repository
          command: git clone -- https://github.com/unchain1ed/webapp.git go/src/github.com/unchain1ed/webapp
      - run: cd server-app
      - run: go version
      - run: pwd
      - run: ls
      - run: go clean -modcache
      # - run: go get -v -t -d ./...
      - run: go mod init github.com/unchain1ed/webapp
      - run: go mod tidy
      - run: go test -v -cover ./...
  build:
    docker:
      - image: cimg/go:1.21.1
    working_directory: /go/src/github.com/unchain1ed/webapp/server-app

    steps:
      - checkout
      - run:
          name: Clone webapp repository
          command: git clone -- https://github.com/unchain1ed/webapp.git go/src/github.com/unchain1ed/webapp
      - run: cd server-app
      - run: go clean -modcache
      - run: pwd
      - run: ls
      # - run: go get -v -t -d ./...
      - run: go mod init github.com/unchain1ed/webapp
      - run: go mod tidy
      - run: go build main.go

workflows:
  version: 2
  test and build:
    jobs:
      - test
      - build
