name: github-actions

on: [push]

jobs:
  # 共通処理
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
        id: go
      - name: check out
        uses: actions/checkout@v3

      # 処理を高速化するために環境をキャッシュ
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  # buildテスト
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: ./server-app
        run:  go build -v ./...

  # testを通す
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        working-directory: ./server-app
        run: go test -v ./...

  # lintを通す
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Change Directory
        working-directory: ./server-app
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

  # Run pwd /home/runner/work/webapp/webapp
  # lint:
  #   needs: setup
  #   runs-on: ubuntu-latestx
  #   steps:
  #     - run: ls
  #     # - run: cd server-app  # インデントされた行でコマンドを実行
  #     - uses: actions/checkout@v3
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: v1.29
